foreach cl [PacketHeader info subclass] {
    puts "# $cl [$cl set hdrlen_]"
}

# PacketHeader/Lms 52
# PacketHeader/PGM 16
# PacketHeader/PGM_SPM 8
# PacketHeader/PGM_NAK 16
# PacketHeader/Pushback 4
# PacketHeader/NV 8
# PacketHeader/LDP 40
# PacketHeader/MPLS 20
# PacketHeader/rtProtoLS 8
# PacketHeader/Ping 24
# PacketHeader/TFRC 48
# PacketHeader/TFRC_ACK 56
# PacketHeader/Diffusion 192
# PacketHeader/RAP 24
# PacketHeader/AODV 804
# PacketHeader/SR 712
# PacketHeader/TORA 32
# PacketHeader/IMEP 512
# PacketHeader/ARP 32
# PacketHeader/MIP 28
# PacketHeader/IPinIP 4
# PacketHeader/LL 32
# PacketHeader/Mac 36
# PacketHeader/Encap 4
# PacketHeader/HttpInval 4
# PacketHeader/MFTP 52
# PacketHeader/SRMEXT 8
# PacketHeader/SRM 16
# PacketHeader/aSRM 8
# PacketHeader/mcastCtrl 20
# PacketHeader/CtrMcast 12
# PacketHeader/rtProtoDV 4
# PacketHeader/GAF 8
# PacketHeader/Snoop 20
# PacketHeader/SCTP 8
# PacketHeader/TCPA 16
# PacketHeader/TCP 76
# PacketHeader/IVS 28
# PacketHeader/RTP 12
# PacketHeader/Message 64
# PacketHeader/Resv 16
# PacketHeader/TCP_QS 12
# PacketHeader/UMP 16
# PacketHeader/Src_rt 76
# PacketHeader/IP 28
# PacketHeader/Common 96
# PacketHeader/Flags 8
# PacketHeader/SDP 16
# PacketHeader/BNEP 24
# PacketHeader/BT 172
